Pinetree (v 23.3.0)
--------------------------------------------------------------------------------
*** Starting Test 'dprxVal_Generator'
2023-09-15_0908_47
--------------------------------------------------------------------------------
Starting MipiDphyGenerator setup
Starting clock config setup
Starting MipiDphyGenerator setup
Starting clock config setup
Starting MipiDphyGenerator setup
Starting clock config setup
Starting MipiDphyGenerator setup
Starting clock config setup
Starting MipiDphyGenerator setup
Starting clock config setup
Starting MipiDphyGenerator setup
Starting clock config setup
Starting MipiDphyGenerator setup
Starting clock config setup
Starting MipiDphyGenerator setup
Starting clock config setup
Starting MipiDphyGenerator setup
Starting clock config setup
Starting MipiDphyGenerator setup
Starting clock config setup
Starting MipiDphyGenerator setup
Starting clock config setup
Starting MipiDphyGenerator setup
Starting clock config setup
Starting MipiDphyGenerator setup
Starting clock config setup
Starting MipiDphyGenerator setup
Starting clock config setup
Starting MipiDphyGenerator setup
Starting clock config setup
Starting MipiDphyGenerator setup
Starting clock config setup
Starting MipiDphyGenerator setup
Starting clock config setup
********************************************************************************
Exception occurred during Test run:
Traceback (most recent call last):
  File "<string>", line 10, in <module>
    (state,time) = coordinator1.getState("Analyzer")
TypeError: cannot unpack non-iterable NoneType object
Test took 8.5 minutes
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dave/Documents/trunk_branch/SvtPython/dftm/pythonForGuiServer.py", line 245, in handleJson
  File "/home/dave/Documents/trunk_branch/SvtPython/dftm/pythonForGuiServer.py", line 197, in wrapped
  File "/home/dave/Documents/trunk_branch/SvtPython/dftm/pythonForGui.py", line 599, in getIESPStatusDict
  File "/home/dave/Documents/trunk_branch/SvtPython/dftm/iespCore.py", line 161, in getStatusDict
  File "/home/dave/Documents/trunk_branch/SvtPython/dftm/iespCore.py", line 319, in getModuleSerialNums
  File "/home/dave/Documents/trunk_branch/SvtPython/dftm/iespSubPart.py", line 1327, in readDataBlock
  File "/home/dave/Documents/trunk_branch/SvtPython/dftm/comm/commUtils.py", line 2339, in readDataBlock
  File "/home/dave/Documents/trunk_branch/SvtPython/dftm/comm/commUtils.py", line 2264, in _readDataBlock
  File "/home/dave/Documents/trunk_branch/SvtPython/dftm/comm/commUtils.py", line 1571, in sendPadding
  File "/home/dave/Documents/trunk_branch/SvtPython/dftm/comm/commUtils.py", line 1556, in sendSpiCommand
  File "/home/dave/Documents/trunk_branch/SvtPython/dftm/comm/commUtils.py", line 257, in sendSpi
  File "/home/dave/Documents/trunk_branch/SvtPython/dftm/comm/commUtils.py", line 96, in spiWrite
  File "/home/dave/Documents/trunk_branch/SvtPython/dftm/comm/ftdi/ftdiSpiInterface.py", line 472, in spiWrite
  File "/home/dave/Documents/trunk_branch/SvtPython/dftm/comm/ftdi/ftdiSpiInterface.py", line 416, in transferBytes
dftm.exceptUtil.FtdiSpiInterfaceException: Failed to obtain 8 bytes. Final queue queries before timing out were : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]. numQueries: 1670Highest queried buffer value: 0
checkConnection: device not responding, so disconnecting
Disconnected IESP.
